# Generated by Django 4.2.3 on 2023-10-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_sets_set_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bests',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
    ]
