# Generated by Django 4.2.3 on 2023-10-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_bests_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='date_used',
            field=models.DateField(auto_now=True),
        ),
    ]
