# Generated by Django 4.2.3 on 2023-10-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_workouts_date_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
