# Generated by Django 4.2.3 on 2023-10-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_workouts_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
