# Generated by Django 4.2.3 on 2023-10-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_workouts_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouts',
            name='svg',
            field=models.IntegerField(default=1),
        ),
    ]
