# Generated by Django 4.2.3 on 2023-09-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='linked_device',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cal_goal',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dairy_goal',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fats_goal',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='fruit_goal',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grains_goal',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='protein_goal',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='veg_goal',
            field=models.IntegerField(default=3),
        ),
        migrations.DeleteModel(
            name='DeviceInfo',
        ),
    ]
