# Generated by Django 4.2.3 on 2023-09-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_linked_device_customuser_cal_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='protein_goal_g',
            field=models.IntegerField(default=100),
        ),
    ]
