# Generated by Django 4.2.3 on 2023-10-29 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_protein_goal_g'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_created',
            field=models.DateField(default=datetime.date(2023, 10, 28)),
        ),
    ]
