# Generated by Django 4.2.3 on 2023-08-18 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('y', 'year'), ('m', 'month'), ('w', 'week'), ('d', 'day')], default='w', max_length=1)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('avg_improvement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('workouts_completed', models.IntegerField()),
                ('avg_protein', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fruit', models.IntegerField()),
                ('veg', models.IntegerField()),
                ('dariy', models.IntegerField()),
                ('fats', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('grains', models.IntegerField()),
                ('cal_in', models.IntegerField()),
                ('cal_out', models.IntegerField()),
                ('net', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
