# Generated by Django 4.2.3 on 2023-10-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='cal_out',
        ),
        migrations.RemoveField(
            model_name='report',
            name='end',
        ),
        migrations.RemoveField(
            model_name='report',
            name='net',
        ),
    ]
