# Generated by Django 4.2.3 on 2023-08-18 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=50)),
                ('kcal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('g_protein', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=50)),
                ('kcal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('g_protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('protein', models.BooleanField()),
                ('fruit', models.BooleanField()),
                ('veg', models.BooleanField()),
                ('grains', models.BooleanField()),
                ('dairy', models.BooleanField()),
                ('fats', models.BooleanField()),
                ('photo', models.FileField(upload_to='uploads/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=50)),
                ('kcal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('g_protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
