# Generated by Django 4.2.3 on 2023-09-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfood',
            name='label',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='meals',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
