# Generated by Django 4.2.3 on 2023-09-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_customfood_label_alter_meals_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='g_protein',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meals',
            name='kcal',
            field=models.IntegerField(),
        ),
    ]
