# Generated by Django 4.2.3 on 2023-10-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_meals_g_protein_alter_meals_kcal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
